repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: check-added-large-files
      - id: forbid-submodules
      - id: end-of-file-fixer
        exclude: dist
      - id: trailing-whitespace
        exclude: dist
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.35.0
    hooks:
      - id: eslint
