# Original: https://github.com/robinraju/release-downloader
name: 'GH-Release-Installer'
description: 'Downloads github releases, unpacks them ands adds to path'
author: 'hegerdes'
inputs:
  repository:
    description: "The source repository path. Expected format {owner}/{repo}"
    default: ${{ github.repository }}
    required: false
  latest:
    description: "A flag to choose between latest release or release tag"
    default: "false"
    required: false
  tag:
    description: "The github tag to download the release from"
    default: ""
    required: false
  fileName:
    description: "Name of the file to download (use '*' to download every assets)"
    default: "*"
    required: false
  out-file-path:
    description: "Relative path under $GITHUB_WORKSPACE to place the downloaded files"
    default: "."
    required: true
  extract:
    description: "If the downladed assets should be extracted to `out-file-path`"
    default: "false"
    required: false
  token:
    description: "GitHub token to access private repos"
    default: ${{ github.token }}
    required: false
  github-api-url:
    description: "The GitHub API URL of the, only use this input if using GitHub Enterprise"
    default: "https://api.github.com"
    required: false
outputs:
  tag_name:
    description: "The github tag used to download the release"

runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "download"
  color: "green"
