name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  # build: # make sure build/ci work properly
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: npm install
  #     - run: npm run all
  test-linux: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          repository: "dvag/aktives-monitoring-tools"
          latest: true
          extract: true
          fileName: "rtf_scheduler_Linux_x86_64.tar.gz"
          token: ${{ secrets.RELEASE_TOKEN }}
      - run: ls -la
      - run: ./rtf_scheduler --version
      - uses: ./
        with:
          repository: "dvag/aktives-monitoring-tools"
          tag: v0.9.1
          extract: true
          fileName: "rtf_scheduler_Linux_x86_64.tar.gz"
          token: ${{ secrets.RELEASE_TOKEN }}
      - run: ls -la
      - run: ./rtf_scheduler --version
  test-windows: # make sure the action works on a clean machine without building
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          repository: "dvag/aktives-monitoring-tools"
          latest: true
          extract: true
          fileName: "rtf_scheduler_Windows_x86_64.zip"
          token: ${{ secrets.RELEASE_TOKEN }}
      - run: dir
      - run: ./rtf_scheduler --version
      - uses: ./
        with:
          repository: "dvag/aktives-monitoring-tools"
          tag: v0.9.1
          extract: true
          fileName: "rtf_scheduler_Windows_x86_64.zip"
          token: ${{ secrets.RELEASE_TOKEN }}
      - run: dir
      - run: ./rtf_scheduler --version
